services:
  meepstudio_website_dev:
    build:
      context: .
      dockerfile: docker/website.Dockerfile
      target: developer
    command: ["pnpm", "run", "dev"]
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      # Mount the packages components (note: this copies EVERYTHING in the packages directory, including node_modules and dist)
      - ./packages:/repo/packages
      # Mount the website app
      - ./apps/website/src:/repo/apps/website/src
      - ./apps/website/app:/repo/apps/website/app
      - ./apps/website/public:/repo/apps/website/public
      - ./apps/website/next.config.ts:/repo/apps/website/next.config.ts
      # Mask the node_modules folders (the less node_modules are copied over, the better/faster)
      - /repo/node_modules
      - /repo/apps/website/node_modules
    working_dir: /repo/apps/website

  meepstudio_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app/